### ISSUE TITLE
After `priceprover build`, the content of `.arith` file changes

### ISSUE THREAD

**Issue by bo-abstrlabs** [AbstrLabs/priceprover#1]
Put `TLSNotaryCheck.arith` in `circuit/`, and run `priceprover build`. Before the run, `TLSNotaryCheck.arith` is 577902367 bytes. And after the run, it will become 577852273 bytes. The two arith are not compatible. If use the old `.arith`, generate pkey and vkey, and use the pkey and vkey for the priceProver.circuit that generated from the new `.arith`, proving will fail.

We need to at least ensure the new `priceProver.circuit` that generated from `TLSNotaryCheck.arith` is always identical and irrevelant to the input. So that the same pkey and vkey can be reused on different input. About why `TLSNotaryCheck.arith` file changes is good to know but optional.

**Comment by Ryuya1995** [comment]
> Before the run, TLSNotaryCheck.arith is 577902367 bytes. And after the run, it will become 577852273 bytes.

This is because the new TLSNotaryCheck.arith is generated by https://github.com/AbstrLabs/priceprover/blob/main/src/main/java/com/abstrlabs/priceprover/circuits/TLSNotaryCheck.java which is slightly different from MPS generated code. (e.g. it changed the white list of key).

> We need to at least ensure the new priceProver.circuit that generated from TLSNotaryCheck.arith is always identical and irrevelant to the input.

It is always identical and irrevelant to the input.
